eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka

jwt:
    validityMs: 7200000

server:
    error:
        include-message: always
    port: 8090
    servlet:
        context-path: /api

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        initialize: true
        password: rar432
        url: jdbc:postgresql://localhost:5434/petshop-auth
        username: postgres
    jackson:
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: true
    jpa:
        defer-datasource-initialization: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                jdbc:
                    time_zone: UTC
    sql:
        init:
            mode: always
