server:
    error:
        include-message: always
    servlet:
        context-path: /api

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
    jackson:
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: true
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                jdbc:
                    time_zone: UTC
