resilience4j:
    bulkhead:
        instances:
            customerGetById:
                maxConcurrentCalls: 10
                maxWaitDuration: 500ms
            customersGetByIdIn:
                maxConcurrentCalls: 10
                maxWaitDuration: 500ms
            vetGetById:
                maxConcurrentCalls: 10
                maxWaitDuration: 500ms
            vetsGetByIdIn:
                maxConcurrentCalls: 10
                maxWaitDuration: 500ms
    circuitbreaker:
        instances:
            customerGetById:
                failureRateThreshold: 60
                slidingWindowSize: 5
            customersGetByIdIn:
                failureRateThreshold: 60
                slidingWindowSize: 5
            vetGetById:
                failureRateThreshold: 60
                slidingWindowSize: 5
            vetsGetByIdIn:
                failureRateThreshold: 60
                slidingWindowSize: 5
server:
    error:
        include-message: always
    port: 8083
    servlet:
        context-path: /api
spring:
    cache:
        type: redis
    datasource:
        driver-class-name: org.postgresql.Driver
        initialize: true
        password: rar432
        url: jdbc:postgresql://localhost:5434/petshop-visit
        username: postgres
    jackson:
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: true
    jpa:
        defer-datasource-initialization: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                jdbc:
                    time_zone: UTC
    redis:
        host: localhost
        port: 6666
    sql:
        init:
            mode: always
