resilience4j:
    bulkhead:
        instances:
            customerGetById:
                maxConcurrentCalls: 10
                maxWaitDuration: 500ms
            customersGetByIdIn:
                maxConcurrentCalls: 10
                maxWaitDuration: 500ms
            vetGetById:
                maxConcurrentCalls: 10
                maxWaitDuration: 500ms
            vetsGetByIdIn:
                maxConcurrentCalls: 10
                maxWaitDuration: 500ms
    circuitbreaker:
        instances:
            customerGetById:
                failureRateThreshold: 60
                slidingWindowSize: 5
            customersGetByIdIn:
                failureRateThreshold: 60
                slidingWindowSize: 5
            vetGetById:
                failureRateThreshold: 60
                slidingWindowSize: 5
            vetsGetByIdIn:
                failureRateThreshold: 60
                slidingWindowSize: 5
server:
    error:
        include-message: always
    servlet:
        context-path: /api

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
    jackson:
        deserialization:
            FAIL_ON_UNKNOWN_PROPERTIES: true
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL10Dialect
                jdbc:
                    time_zone: UTC
